# Wishlist deployment yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-producer
  labels:
    app: producer
spec:
  replicas: 1 #We always want more than 1 replica for HA
  selector:
    matchLabels:
      app: producer 
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: yahel777/my-rmqp-example_producer:v6
#        ports:
#        - containerPort: 5001