apiVersion: v1
kind: Pod
metadata:
  name: producer
  labels: 
    app: producer
spec:
  containers:
  - name: producer
    image: yahel777/my-rmqp-example_producer:v6
    command: ["python"]
#    args: ["HOSTNAME", "KUBERNETES_PORT"]
    args: ["producer.py", "-p", "5672", "-s", $(server), "-m", "my message", "-r", "400"]
#    producer.py -p 5672 -s 100.26.247.242 -m "check it out" -r 300
    env:
    - name: server
      value: "100.26.247.242"

  restartPolicy: OnFailure