apiVersion: v1
kind: Pod
metadata:
  name: consumer
  labels: 
    app: consumer
spec:
  containers:
  - name: consumer
    image: yahel777/consumer:5
    command: ["python"]
#    args: ["HOSTNAME", "KUBERNETES_PORT"]
    args: ["consumer.py", "-s", $(server)]
#    consumer.py  -s 100.26.247.242 > var/mq/1.txt
    env:
    - name: server
      value: "100.26.247.242"
    volumeMounts:
        - name: mq-persistent-storage
          mountPath: /var/mq
  volumes:
  - name: mq-persistent-storage
    persistentVolumeClaim:
      claimName: mq-pv-claim